### ISSUE TITLE
做了个 Web 版

### ISSUE THREAD

**Issue by mercutiojohn** [PairZhu/HuiHuTong#2]
做了个 Web 版：https://github.com/mercutiojohn/hht-web

**Comment by PairZhu** [comment]
不错不错，我当初没考虑网页方案主要是考虑到这样就失去了秒开的优势了，但是现在想想用pwa做应该也能实现秒开。大佬不妨把它改成纯离线的pwa应用？

**Comment by mercutiojohn** [comment]
可以搞一下看看

**Comment by mercutiojohn** [comment]
已合入master，谢大佬贡献哇！
